import Head from 'next/head'
import {Inter} from 'next/font/google'
import ClientInfo from "@/components/clientInfo";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>MA Zainul Hasan 1 Genggong</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div className="table-title">
                    <center>
                        <h3>API Server MA Zainul Hasan 1 Genggong</h3>
                    </center>
                </div>
                <table className="table-fill">
                    <thead>
                    <tr>
                        <th className="text-left">#</th>
                        <th className="text-left">Info</th>
                    </tr>
                    </thead>
                    <tbody className="table-hover">
                    <tr>
                        <td className="text-left">API Server</td>
                        <td className="text-left">Running</td>
                    </tr>
                    </tbody>
                </table>
                <br/>
                <ClientInfo/>
                <br/>
            </main>
        </>
    )
}
